apiVersion: v1
kind: Service
metadata:
  name: bahmni-config
  labels:
    app: bahmni-config
spec:
  selector:
    app: bahmni-config
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8901
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: bahmni-config
  annotations:
    traefik.k8s.io/root-app: /bahmni-config
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: bahmni-config
          servicePort: 80
        path: /bahmni-config
