apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-config
spec:
  selector:
    matchLabels:
      app: bahmni-config
  template:
    metadata:
      labels:
        app: bahmni-config
    spec:
      volumes:
        - name: httpd-config-volume
          confiMap:
            name:  bahmni-config-httpd
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
      containers:
      - name: bahmni-config
        image: mekomsolutions/metabase
        volumeMounts:
            - name: httpd-config-volume
              mountPath: "/usr/local/apache2/conf/httpd.conf"
            - name: distro
              mountPath: "/var/www"
              subPath: "bahmni_config/"
        ports:
        - containerPort: 3000
