apiVersion: v1
kind: ConfigMap
metadata:
  name: openmrs-props
  labels:
    app: openmrs
data:
  erp.properties: |
    erp.host=${ODOO_HOST}
    erp.port=8069
    erp.user=${ODOO_USER}
    erp.password=${ODOO_PASSWORD}
    erp.database=${ODOO_DB}

  bahmnicore.properties: |
    bahmnicore.images.directory=/home/bahmni/patient_images
    bahmnicore.images.directory.defaultImage=/home/bahmni/patient_images/blank-user.png
    bahmnicore.urls.patientimages=/patient_images
    bahmnicore.documents.baseDirectory=/home/bahmni/document_images

    feed.maxFailedEvents=10000
    feed.connectionTimeoutInMilliseconds=10000
    feed.replyTimeoutInMilliseconds=20000

    openelis.uri=http://openelis:8080/
    openelis.user=atomfeed
    openelis.password=AdminadMIN*
    patient.feed.uri=http://openelis:8080/openelis/ws/feed/patient/recent
