apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-scripts
data:
  create_odoo_db.sh: |
    #!/bin/bash

    set -eu

    function create_user() {
      local user=$1
      local password=$2
      echo "  Creating '$user' user..."
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" $POSTGRES_DB <<-EOSQL
          CREATE USER $user WITH UNENCRYPTED PASSWORD '$password';
          ALTER USER $user CREATEDB;
    EOSQL
    }

    create_user ${ODOO_DB_USER} ${ODOO_DB_PASSWORD}
  create_metabase_db.sh: |
    #!/bin/bash

    set -eu

    function create_user_and_database() {
      local database=$1
      local user=$2
      local password=$3
      echo "  Creating '$user' user and '$database' database..."
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" $POSTGRES_DB <<-EOSQL
          CREATE USER $user WITH UNENCRYPTED PASSWORD '$password';
          CREATE DATABASE $database;
          GRANT ALL PRIVILEGES ON DATABASE $user TO $database;
    EOSQL
    }

    create_user_and_database ${METABASE_DB_NAME} ${METABASE_DB_USER} ${METABASE_DB_PASSWORD}
  create_analytics_db.sh: |
    #!/bin/bash

    set -eu

    function create_user_and_database() {
      local database=$1
      local user=$2
      local password=$3
      echo "  Creating '$user' user and '$database' database..."
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" $POSTGRES_DB <<-EOSQL
          CREATE USER $user WITH UNENCRYPTED PASSWORD '$password';
          CREATE DATABASE $database;
          GRANT ALL PRIVILEGES ON DATABASE $user TO $database;
    EOSQL
    }

    create_user_and_database ${ANALYTICS_DB_NAME} ${ANALYTICS_DB_USER} ${ANALYTICS_DB_PASSWORD}
