apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      volumes:
        - name: odoo-props
          configMap:
            name: odoo-conf
        - name:  distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      containers:
      - name: odoo
        image: mekomsolutions/odoo
        volumeMounts:
            - name: odoo-props
              mountPath: "/etc/properties/"
            - name: distro
              subPath: "odoo_config/"
              mountPath: "/opt/odoo-config"
            - name: distro
              subPath: "odoo_addons/"
              mountPath: "/mnt/extra-addons"
            - name: data
              subPath: "odoo/filestore"
              mountPath: "/var/lib/odoo/filestore"
            - name: distro
              subPath: "openmrs_config/"
              mountPath: "/opt/openmrs-config"
        ports:
        - containerPort: 8069
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configs
                key: POSTGRES_HOST
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-configs
                key: POSTGRES_PORT
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_USER
          - name: PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_NAME
          - name: ODOO_MASTER_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_MASTER_PASSWORD
