{{ if .Values.apps }}{{ if .Values.apps.metabase }} {{ if .Values.apps.metabase.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  {{ if .Values.apps.metabase.service.loadBalancerIP }}loadBalancerIP: {{ .Values.apps.metabase.service.loadBalancerIP }} {{ end }}
  type: LoadBalancer
  selector:
    app: metabase
  ports:
  - port: {{ .Values.apps.metabase.service.port }}
    targetPort: 3000
{{ end }}{{ end }}{{ end }}