{{ if .Values.apps }}{{ if .Values.apps.metabase }} {{ if .Values.apps.metabase.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      volumes:
        - name: metabase-db-config
          configMap:
            name: metabase-db
      initContainers:
        - name: init-db
          image: "{{ .Values.apps.metabase.initImage }}"
          volumeMounts:
            - name: metabase-db-config
              mountPath: "/mnt/"      
          command: ['sh', '-c', "bash /mnt/create_metabase_db.sh"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
            - name: MB_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: metabase-configs
                  key: METABASE_DB_USER
            - name: MB_DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: metabase-configs
                  key: METABASE_DB_NAME
            - name: MB_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: metabase-configs
                  key: METABASE_DB_PASSWORD
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
      containers:
      - name: metabase
        image: "{{ .Values.apps.metabase.image }}"
        resources:
            requests:
              memory: "{{  .Values.apps.metabase.resources.requests.memory }}"
              cpu: "{{ .Values.apps.metabase.resources.requests.cpu }}"
        ports:
        - name: metabase-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/health
            port: metabase-port
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: metabase-port
          initialDelaySeconds: 10
          periodSeconds: 20
        env:
          - name: MB_DB_TYPE
            value: postgres
          - name: MB_DB_PORT
            value: "5432"
          - name: MB_DB_USER
            valueFrom:
              configMapKeyRef:
                name: metabase-configs
                key: METABASE_DB_USER
          - name: MB_DB_DBNAME
            valueFrom:
              configMapKeyRef:
                name: metabase-configs
                key: METABASE_DB_NAME
          - name: MB_DB_PASS
            valueFrom:
              configMapKeyRef:
                name: metabase-configs
                key: METABASE_DB_PASSWORD
          - name: MB_DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
{{ end }}{{ end }}{{ end }}