---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
