kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: distro-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.rwxStorageClass }}
  accessModes:
    - ReadWriteMany
