apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configs
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: password
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
