{{ if .Values.apps }}{{ if .Values.apps.odoo }} {{ if .Values.apps.odoo.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  {{ if .Values.apps.odoo.service.loadBalancerIP }}loadBalancerIP: {{ .Values.apps.odoo.service.loadBalancerIP }} {{ end }}
  type: LoadBalancer
  selector:
    app: odoo
  ports:
  - port: {{ .Values.apps.odoo.service.port }} 
    targetPort: 8069
{{ end }}{{ end }}{{ end }}