{{ if .Values.apps }}{{ if .Values.apps.odoo }} {{ if .Values.apps.odoo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker2
      volumes:
        - name: odoo-db
          configMap:
            name: odoo-db
        - name: odoo-props
          configMap:
            name: odoo-conf
        - name:  distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      initContainers:
        - name: init-db
          image: "{{ .Values.apps.odoo.initImage }}"
          volumeMounts:
            - name: odoo-db
              mountPath: "/mnt/"
          command: ['sh', '-c', "bash /mnt/create_odoo_role.sh"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
            # Odoo Vars
            - name: ODOO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: odoo-configs
                  key: ODOO_DB_NAME
            - name: ODOO_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: odoo-configs
                  key: ODOO_DB_USER
            - name: ODOO_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: odoo-configs
                  key: ODOO_DB_PASSWORD
      containers:
      - name: odoo
        image: "{{ .Values.apps.odoo.image }}"
        resources:
            requests:
              memory: "{{  .Values.apps.odoo.resources.requests.memory }}"
              cpu: "{{ .Values.apps.odoo.resources.requests.cpu }}"
        volumeMounts:
            - name: odoo-props
              mountPath: "/etc/properties/"
            - name: distro
              subPath: "odoo_config/"
              mountPath: "/opt/odoo-config"
            - name: distro
              subPath: "odoo_addons/"
              mountPath: "/mnt/extra-addons"
            - name: distro
              subPath: "openmrs_config/"
              mountPath: "/opt/openmrs-config"
            - name: data
              subPath: "odoo/filestore"
              mountPath: "/var/lib/odoo/filestore"
            - name: data
              subPath: "odoo/odoo-config_checksum"
              mountPath: "/opt/odoo-config_checksum"
            - name: data
              subPath: "odoo/openmrs-config_checksum"
              mountPath: "/opt/openmrs-config_checksum"
        ports:
        - name: http
          containerPort: 8069
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 50
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configs
                key: POSTGRES_HOST
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-configs
                key: POSTGRES_PORT
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_USER
          - name: PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_NAME
          - name: ODOO_MASTER_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_MASTER_PASSWORD
          - name: INITIALIZER_DATA_FILES_PATH
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: INITIALIZER_DATA_FILES_PATH
          - name: INITIALIZER_CONFIG_FILE_PATH
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: INITIALIZER_CONFIG_FILE_PATH
          - name: ADDONS
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ADDONS
{{ end }}{{ end }}{{ end }}
