apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-config
  labels:
    app: odoo-connect
data:
  erp.properties: |
    erp.host=${ODOO_HOST}
    erp.port=8069
    erp.user=${ODOO_USER}
    erp.password=${ODOO_PASSWORD}
    erp.database=${ODOO_DB}