apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-connect
spec:
  selector:
    matchLabels:
      app: odoo-connect
  template:
    metadata:
      labels:
        app: odoo-connect
    spec:
      volumes:
        - name: erp-config-volume
          configMap:
            name:  erp-config
      containers:
      - name: odoo-connect
        image: mekomsolutions/odoo-connect
        volumeMounts:
            - name: erp-config-volume
              mountPath: "/usr/local/tomcat/erp-atomfeed.properties"
        env:
          - name: ODOO_DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: postgres-configs
                key: POSTGRES_HOST
          - name: ODOO_DB
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_NAME
          - name: ODOO_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_USER
          - name: ODOO_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_DB_PASSWORD
          - name: ODOO_HOST
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_HOST
          - name: ODOO_USERNAME
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_USER
          - name: ODOO_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: odoo-configs
                key: ODOO_PASSWORD
          - name: OPENMRS_HOST
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_HOST
          - name: OPENMRS_USER
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_USER
          - name: OPENMRS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_PASSWORD
          - name: OPENELIS_HOST
            value: openelis
          - name: OPENELIS_USER
            value: openelis
          - name: OPENELIS_PASSWORD
            value: password
          - name: APP_PROPERTIES_FILE
            value: "/usr/local/tomcat/erp-atomfeed.properties"
