apiVersion: v1
kind: Service
metadata:
  name: implementer-interface
  labels:
    app: implementer-interface
spec:
  selector:
    app: implementer-interface
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8902
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: implementer-interface
  anntation:
    traefik.k8s.io/root-app: /implementer-interface
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: implementer-interface
          servicePort: 80
        path: /implementer-interface