apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-configs
  labels:
    app: odoo
data:
  ODOO_DB_USER: odoo
  ODOO_DB_PASSWORD: password
  ODOO_DB_NAME: odoo
  ODOO_HOST: odoo 
  ODOO_USER: admin
  ODOO_PASSWORD: admin
  ODOO_MASTER_PASSWORD: password
  ODOO_PUBLIC_PORT: "8069"
  ODOO_EXTRA_ADDONS: odoo_addons
  ODOO_CONFIG_PATH: odoo_config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configs
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: password
  POSTGRES_DB: postgres 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openmrs-configs
  labels:
    app: openmrs
data:
  OPENMRS_DB_NAME: openmrs
  OPENMRS_USER: superman
  OPENMRS_PASSWORD: Admin123
  OPENMRS_HOST: openmrs
  OPENMRS_DB_USER: openmrs
  OPENMRS_DB_HOST: mysql
  OPENMRS_DB_PASSWORD: password
  OPENMRS_OWAS_PATH: openmrs_core
  OPENMRS_MODULES_PATH: openmrs_modules
  OPENMRS_CONFIG_PATH: openmrs_config
  OPENMRS_CONFIG_CHECKSUMS_PATH: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configs
  labels:
    app: mysql
data:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bahmni-configs
  labels:
    app: bahmni
data:
  TIMEZONE: UTC
  BAHMNI_CONFIG_PATH: ""
  BAHMNI_APPS_PATH: bahmni_emr/bahmniapps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-configs
data:
  METABASE_DB_NAME: metabase
  METABASE_DB_USER: metabase
  METABASE_DB_PASSWORD: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-configs
data:
  ANALYTICS_DB_NAME: analytics
  ANALYTICS_DB_USER: analytics
  ANALYTICS_DB_PASSWORD: password
