apiVersion: v1
kind: Service
metadata:
  name: openmrs
  labels:
    app: openmrs
spec:
  selector:
    app: openmrs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openmrs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /openmrs
spec:
  rules:
  - http:
      paths:
      - path: /openmrs
        pathType: Prefix
        backend:
          service:
            name: openmrs
            port:
              number: 80
