apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
spec:
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        app: openmrs
    spec:
      volumes:
        - name: openmrs-props
          configMap:
            name: openmrs-props
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      containers:
      - name: openmrs
        image: mekomsolutions/openmrs
        volumeMounts:
            - name: distro
              subPath: "openmrs_modules/"
              mountPath: "/usr/local/tomcat/.OpenMRS/modules"
            - name: distro
              mountPath: "/usr/local/tomcat/.OpenMRS/configuration"
              subPath: "openmrs_config/"
            - name: openmrs-props
              mountPath: "/etc/properties"
            - name: data
              subPath: "openmrs/bahmni_filestore"
              mountPath: "/usr/local/tomcat/.OpenMRS/bahmni_filestore"
            - name: data
              subPath: "openmrs/configuration_checksums"
              mountPath: "/usr/local/tomcat/.OpenMRS/configuration_checksums/"
        ports:
        - containerPort: 8080
        env:
          - name: MODULE_WEB_ADMIN
            value: "true"
          - name: DB_AUTO_UPDATE
            value: "true"
          - name: DB_CREATE_TABLES
            value: "true"
          - name: DB_HOST
            value: mysql
          - name: DB_DATABASE
            value: openmrs
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_PASSWORD
