apiVersion: v1
kind: Service
metadata:
  name: bahmniapps
  labels:
    app: bahmniapps
spec:
  selector:
    app: bahmniapps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8900
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bahmniapps
spec:
  rules:
  - http:
      paths:
      - path: /bahmniapps
        pathType: Prefix
        backend:
          service:
            name: bahmniapps
            port:
              number: 80
      - path: /bahmni
        pathType: Prefix
        backend:
          service:
            name: bahmniapps
            port:
              number: 80
      - path: /cgi-bin/systemdate
        pathType: Prefix
        backend:
          service:
            name: bahmniapps
            port:
              number: 80