apiVersion: v1
kind: Service
metadata:
  name: bahmniapps
  labels:
    app: bahmniapps
spec:
  selector:
    app: bahmniapps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8900
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: bahmniapps
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /bahmni
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: bahmniapps
          servicePort: 80
        path: /bahmniapps
      - backend:
          serviceName: bahmniapps
          servicePort: 80
        path: /bahmni
      - backend:
          serviceName: bahmniapps
          servicePort: 80
        path: /cgi-bin/systemdate
