apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmniapps
spec:
  selector:
    matchLabels:
      app: bahmniapps
  template:
    metadata:
      labels:
        app: bahmniapps
    spec:
      volumes:
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
      containers:
      - name: bahmniapps
        image: mekomsolutions/bahmniapps
        volumeMounts:
            - name: distro
              subPath: "bahmni_emr/bahmniapps"
              mountPath: "/var/www/bahmni"
        ports:
        - containerPort: 8900
