apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-database
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: mysql
          image: mariadb:10.3
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-database
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_NAME
            - name: MYSQL_USER 
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-configs
                  key: MYSQL_ROOT_PASSWORD
      nodeSelector:
        role: database
