{{ if .Values.apps }}{{ if .Values.apps.bahmni_filestore }} {{ if .Values.apps.bahmni_filestore.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: bahmni-filestore
  labels:
    app: bahmni-filestore
spec:
  selector:
    app: bahmni-filestore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
{{ end }}{{ end }}{{ end }}