{{ if .Values.apps }}{{ if .Values.apps.proxy }} {{ if .Values.apps.proxy.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  type: LoadBalancer
  {{ if .Values.apps.proxy.service.loadBalancerIP }}loadBalancerIP: {{ .Values.apps.proxy.service.loadBalancerIP }} {{ end }}
  selector:
    app: proxy
  ports:
  - port: {{ .Values.apps.proxy.service.port }}
    targetPort: 80
{{ end }}{{ end }}{{ end }}