{{ if .Values.apps }}{{ if .Values.apps.proxy }} {{ if .Values.apps.proxy.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: "{{ .Values.apps.proxy.image }}" 
        resources:
            requests:
              memory: "{{  .Values.apps.proxy.resources.requests.memory }}"
              cpu: "{{ .Values.apps.proxy.resources.requests.cpu }}"
        command: ["httpd-foreground"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: proxy-rules-volume
          mountPath: /usr/local/apache2/conf/rules
        - name: proxy-config-volume
          mountPath: /usr/local/apache2/conf/extra
      volumes:
      - name: proxy-rules-volume
        configMap:
          name: proxy-rules
      - name: proxy-config-volume
        configMap:
          name: proxy-confs
{{ end }}{{ end }}{{ end }}