apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-confs
data:
  000-80.conf: |
    <VirtualHost *:80>
    include  /usr/local/apache2/conf/rules/proxy-rules

    <IfDefine enableTLS>
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R=temp,L]
    </IfDefine>
    </VirtualHost>
  010-443.conf: |
    <VirtualHost *:443>
    include  /usr/local/apache2/conf/proxy-rules
    <IfDefine enableTLS>
    LoadModule ssl_module modules/mod_ssl.so
    SSLEngine on
    SSLCertificateFile "/etc/tls/cert.pem"
    SSLCertificateKeyFile "/etc/tls/privkey.pem"
    #SSLCertificateChainFile "/etc/tls/chain.pem"
    </IfDefine>
    </VirtualHost>