{{ if .Values.apps }}{{ if .Values.apps.backup_services }} {{ if .Values.apps.backup_services.enabled }} {{ if .Values.isAppliance }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: backup-services-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-services-pv
spec:
  capacity:
    storage: {{  .Values.apps.backup_services.storage.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: backup-services-storage
  local:
    path: {{ .Values.apps.backup_services.localPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-services-pvc
  labels:
    app: backup-services
spec:
  storageClassName: backup-services-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{  .Values.apps.backup_services.storage.size }}
{{ end }}{{ end }}{{ end }}{{ end }}