{{ if .Values.apps }}{{ if .Values.apps.openelis }} {{ if .Values.apps.openelis.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: openelis
  labels:
    app: openelis
spec:
  type: ClusterIP
  selector:
    app: openelis
  ports:
  - port: 8080
    targetPort: 8080
{{ end }}{{ end }}{{ end }}