apiVersion: v1
kind: Service
metadata:
  name: bahmni-filestore
  labels:
    app: bahmni-filestore
spec:
  selector:
    app: bahmni-filestore
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: bahmni-filestore
  annotations:
    traefik.k8s.io/root-app: /bahmni-filestore
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: bahmni-filestore
          servicePort: 80
        path: /bahmni-filestore
