{{ if .Values.apps }}{{ if .Values.apps.bahmniapps }} {{ if .Values.apps.bahmniapps.enabled }} 
apiVersion: v1
kind: Service
metadata:
  name: bahmniapps
  labels:
    app: bahmniapps
spec:
  selector:
    app: bahmniapps
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8900
{{ end }}{{ end }}{{ end }}