apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: bahmni-config
        image: mekomsolutions/appointments
        ports:
        - containerPort: 8903
