name: CI

on:
  push:
    branches: [ main ]

env:
  REPO_USER: ${{ secrets.NEXUS_USERNAME }}
  REPO_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  REPO_URL: https://nexus.mekomsolutions.net/repository/helm/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
      - 
        name: Install yq
        run: pip3 install yq
      - 
        name: Rerieve chart version
        run: |
            VERSION=$(yq -r .version helm/bahmni/Chart.yaml)
            echo "::set-env name=CHART_VERSION::$VERSION"
      - 
        name: Package and push
        run: |
          helm package helm/bahmni
          curl -u $REPO_USER:$REPO_PASSWORD $REPO_URL --upload-file bahmni-helm-$CHART_VERSION.tgz
        env:
          CHART_VERSION: ${{ env.CHART_VERSION }}
